import { Platform, StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Platform.OS === 'web' ? 4 : 7,
    marginBottom: Platform.OS === 'web' ? 12 : 0,
    marginTop: Platform.OS === 'web' ? 0 : 12,
  },
  backText: {
    color: '#2FC4B1',
    fontSize: 14,
    fontFamily: 'SulphurPoint',
  },
  title: {
    fontSize: Platform.OS === 'web' ? 31 : 28,
    fontWeight: '800',
    color: '#117C72',
    letterSpacing: Platform.OS === 'web' ? 0 : 2,
    marginBottom: Platform.OS === 'web' ? 22 : 0,
    marginTop: Platform.OS === 'web' ? 0 : 16,
    fontFamily: 'SulphurPointBold',
  },
  label: {
    fontSize: Platform.OS === 'web' ? 14 : 17,
    fontWeight: '600',
    color: Platform.OS === 'web' ? '#117C72' : '#2FC4B1',
    marginBottom: Platform.OS === 'web' ? 4 : 3,
    marginTop: Platform.OS === 'web' ? 14 : 20,
    letterSpacing: Platform.OS === 'web' ? 0.5 : 0,
    fontFamily: 'SulphurPointBold',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: Platform.OS === 'web' ? 0 : 1.5,
    borderBottomColor: '#2FC4B1',
    paddingBottom: Platform.OS === 'web' ? 0 : 5,
    marginBottom: Platform.OS === 'web' ? 6 : 0,
    ...(Platform.OS === 'web'
      ? {
          borderWidth: 1,
          borderColor: '#DCECE7',
          borderRadius: 10,
          paddingHorizontal: 12,
          paddingVertical: 5,
          backgroundColor: '#F8FFFC',
        }
      : null),
  },
  input: {
    flex: 1,
    fontSize: Platform.OS === 'web' ? 16 : 15,
    color: '#575757',
    fontFamily: 'PoppinsRegular',
    paddingVertical: 2,
  },
  helpRow: {
    marginTop: Platform.OS === 'web' ? 18 : 15,
    alignItems: Platform.OS === 'web' ? 'stretch' : 'flex-start',
  },
  secondaryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'web' ? 8 : 10,
    borderRadius: Platform.OS === 'web' ? 10 : 999,
    backgroundColor: '#F4FBF9',
    borderWidth: 1,
    borderColor: '#D7F2EB',
  },
  secondaryPillText: {
    color: '#117C72',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'PoppinsSemiBold',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2FC4B1',
    borderRadius: Platform.OS === 'web' ? 10 : 30,
    paddingVertical: Platform.OS === 'web' ? 9 : 16,
    marginTop: Platform.OS === 'web' ? 28 : 16,
    gap: 8,
    shadowColor: '#2FC4B1',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: 'PoppinsSemiBold',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
  },
  linkText: {
    fontSize: 14,
    color: '#9AA8A0',
    fontFamily: 'PoppinsRegular',
  },
  linkBold: {
    color: '#2FC4B1',
    fontWeight: '700',
    fontFamily: 'PoppinsSemiBold',
  },
});
