import { Platform, StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Platform.OS === 'web' ? 4 : 7,
    marginBottom: Platform.OS === 'web' ? 12 : 8,
    marginTop: Platform.OS === 'web' ? 0 : 8,
  },
  backText: {
    color: '#2FC4B1',
    fontSize: 14,
    fontFamily: 'SulphurPoint',
  },
  title: {
    fontSize: Platform.OS === 'web' ? 31 : 28,
    fontWeight: '800',
    color: '#117C72',
    letterSpacing: Platform.OS === 'web' ? 0 : 2,
    marginBottom: Platform.OS === 'web' ? 18 : 0,
    marginTop: Platform.OS === 'web' ? 0 : 16,
    fontFamily: 'SulphurPointBold',
  },
  photoButton: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 0 : 10,
    right: Platform.OS === 'web' ? 0 : 18,
    width: Platform.OS === 'web' ? 68 : 76,
    height: Platform.OS === 'web' ? 68 : 76,
    backgroundColor: '#F7FFFC',
    borderRadius: Platform.OS === 'web' ? 18 : 38,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0000003d',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D3F2EB',
  },
  photoPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7FFFC',
  },
  photoPreview: {
    width: '100%',
    height: '100%',
  },
  photoText: {
    fontSize: 10,
    color: '#2FC4B1',
    fontWeight: '600',
    marginTop: 2,
    textAlign: 'center',
  },
  photoHint: {
    marginTop: Platform.OS === 'web' ? 16 : 28,
    marginBottom: 0,
    fontSize: 12,
    color: '#8AA69C',
    fontFamily: 'PoppinsRegular',
  },
  label: {
    fontSize: Platform.OS === 'web' ? 14 : 17,
    fontWeight: '600',
    color: Platform.OS === 'web' ? '#117C72' : '#2FC4B1',
    marginBottom: Platform.OS === 'web' ? 4 : 3,
    marginTop: Platform.OS === 'web' ? 14 : 20,
    letterSpacing: Platform.OS === 'web' ? 0.5 : 0,
    fontFamily: 'SulphurPointBold',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: Platform.OS === 'web' ? 0 : 1.5,
    borderBottomColor: '#2FC4B1',
    paddingBottom: Platform.OS === 'web' ? 0 : 5,
    marginBottom: Platform.OS === 'web' ? 6 : 0,
    ...(Platform.OS === 'web'
      ? {
          borderWidth: 1,
          borderColor: '#DCECE7',
          borderRadius: 10,
          paddingHorizontal: 12,
          paddingVertical: 5,
          backgroundColor: '#F8FFFC',
        }
      : null),
  },
  inputIcon: {
    marginRight: 5,
  },
  input: {
    flex: 1,
    fontSize: Platform.OS === 'web' ? 16 : 15,
    color: '#575757',
    fontFamily: 'PoppinsRegular',
    paddingVertical: 2,
  },
  passwordHint: {
    marginTop: Platform.OS === 'web' ? 12 : 15,
    fontSize: 12,
    color: '#8AA69C',
    fontFamily: 'PoppinsRegular',
  },
  dropdown: {
    backgroundColor: Platform.OS === 'web' ? '#F8FFFC' : 'transparent',
    borderRadius: Platform.OS === 'web' ? 10 : 0,
    marginTop: 7,
    marginBottom: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Platform.OS === 'web' ? '#DCECE7' : '#FCFCFC',
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'web' ? 8 : 12,
    borderBottomWidth: 1,
    borderBottomColor: Platform.OS === 'web' ? '#DCECE7' : '#05ed946e',
  },
  dropdownText: {
    fontSize: 15,
    color: '#9AA8A0',
    fontFamily: 'PoppinsRegular',
  },
  dropdownTextActive: {
    color: '#2FC4B1',
    fontWeight: '600',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2FC4B1',
    borderRadius: Platform.OS === 'web' ? 10 : 30,
    paddingVertical: Platform.OS === 'web' ? 9 : 16,
    marginTop: Platform.OS === 'web' ? 24 : 16,
    gap: 8,
    shadowColor: '#2FC4B1',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: 'PoppinsSemiBold',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
  },
  linkText: {
    fontSize: 14,
    color: '#9AA8A0',
    fontFamily: 'PoppinsRegular',
  },
  linkBold: {
    color: '#2FC4B1',
    fontWeight: '700',
    fontFamily: 'PoppinsSemiBold',
  },
});
