import { auth, db } from './firebase.js';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js';
import { addDoc, arrayUnion, collection, deleteDoc, doc, getDoc, onSnapshot, serverTimestamp, setDoc, updateDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js';

const state = { users: [], programas: [], fichas: [], trimestres: [], competencias: [], raps: [], rapAssignments: [], profile: null, pendingPhoto: null, unsubscribers: [], editingProgram: null, editingFicha: null, editingTrimester: null };
const authModal = document.querySelector('#auth-modal');
const appView = document.querySelector('#admin-app');
const loginMessage = document.querySelector('#login-message');
const $ = (selector) => document.querySelector(selector);
const text = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const normalRole = (role) => String(role || '').trim().toLocaleLowerCase();
const isAdmin = (profile) => ['administrador', 'admin'].includes(normalRole(profile?.rol));
const initials = (name = 'Administrador') => name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

document.querySelector('.menu-toggle')?.addEventListener('click', () => { const nav = $('.nav'); const open = nav.classList.toggle('open'); $('.menu-toggle').setAttribute('aria-expanded', String(open)); });
document.querySelectorAll('.open-auth').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); authModal.showModal(); }));
$('[data-close-auth]')?.addEventListener('click', () => authModal.close());

$('#login-form')?.addEventListener('submit', async (event) => {
  event.preventDefault(); loginMessage.textContent = 'Comprobando acceso…'; loginMessage.className = 'form-message';
  const button = event.currentTarget.querySelector('button'); button.disabled = true;
  try { await signInWithEmailAndPassword(auth, $('#email').value.trim(), $('#password').value); }
  catch (error) { loginMessage.textContent = error.code === 'auth/invalid-credential' ? 'Correo o contraseña incorrectos.' : 'No fue posible iniciar sesión. Intenta de nuevo.'; loginMessage.className = 'form-message error'; button.disabled = false; }
});

onAuthStateChanged(auth, async (user) => {
  state.unsubscribers.splice(0).forEach((unsubscribe) => unsubscribe());
  if (!user) return showLanding();
  try {
    const userRef = doc(db, 'usuarios', user.uid);
    const profileDoc = await getDoc(userRef);
    let profile = profileDoc.exists() ? profileDoc.data() : null;
    let profileRestored = false;
    if (!user.emailVerified) throw new Error('Debes verificar tu correo antes de ingresar.');
    if (!profile) {
      profile = {
        uid: user.uid,
        nombre: user.displayName?.trim() || user.email?.split('@')[0] || 'Aprendiz',
        correo: user.email || '',
        rol: 'Aprendiz',
        fotoUrl: user.photoURL || null,
        correoVerificado: true,
      };
      await setDoc(userRef, { ...profile, creadoEn: serverTimestamp(), actualizadoEn: serverTimestamp() });
      profileRestored = true;
    }
    if (profileRestored) {
      loginMessage.textContent = 'Perfil restaurado como Aprendiz.';
      loginMessage.className = 'form-message success';
      authModal.showModal();
      await signOut(auth);
      return;
    }
    if (!isAdmin(profile)) {
      const roleLabel = profile?.rol?.trim() || 'sin rol';
      throw new Error(`Esta cuenta está registrada como ${roleLabel}. El acceso web está reservado para administradores.`);
    }
    showAdmin(profile); subscribeData();
  } catch (error) { loginMessage.textContent = error.message; loginMessage.className = 'form-message error'; authModal.showModal(); $('#login-form button[type="submit"]').disabled = false; await signOut(auth); }
});

function showLanding() { appView.hidden = true; $('main').hidden = false; $('footer').hidden = false; $('.header').hidden = false; }
function showAdmin(profile) { state.profile = profile; authModal.close(); $('main').hidden = true; $('footer').hidden = true; $('.header').hidden = true; appView.hidden = false; $('#account-name').textContent = profile.nombre || 'Administrador'; $('#admin-short-name').textContent = (profile.nombre || 'Administrador').split(' ')[0]; $('#account-avatar').textContent = initials(profile.nombre); renderProfile(); }
function renderProfile() { if (!state.profile || !$('#profile-name')) return; const profile = state.profile; $('#profile-name').value = profile.nombre || ''; $('#profile-email').value = profile.correo || auth.currentUser?.email || ''; $('#profile-role').value = profile.rol || 'Administrador'; $('#profile-initials').textContent = initials(profile.nombre); if (profile.fotoUrl) { $('#profile-image').src = profile.fotoUrl; $('#profile-image').hidden = false; $('#profile-initials').hidden = true; } else { $('#profile-image').hidden = true; $('#profile-initials').hidden = false; } }
function ordered(snapshot) { return snapshot.docs.map((item) => ({ id: item.id, ...item.data() })).sort((a, b) => (b.creadoEn?.toMillis?.() || 0) - (a.creadoEn?.toMillis?.() || 0)); }
function subscribeData() {
  state.unsubscribers.push(onSnapshot(collection(db, 'usuarios'), (snapshot) => { state.users = ordered(snapshot); renderUsers(); renderSummary(); }, dataError));
  state.unsubscribers.push(onSnapshot(collection(db, 'programas'), (snapshot) => { state.programas = ordered(snapshot); renderAcademic(); renderSummary(); }, dataError));
  state.unsubscribers.push(onSnapshot(collection(db, 'fichas'), (snapshot) => { state.fichas = ordered(snapshot); renderAcademic(); renderTrimester(); renderSummary(); }, dataError));
  state.unsubscribers.push(onSnapshot(collection(db, 'trimestres'), (snapshot) => { state.trimestres = ordered(snapshot); renderTrimester(); }, dataError));
  state.unsubscribers.push(onSnapshot(collection(db, 'competencias'), (snapshot) => { state.competencias = ordered(snapshot); renderAcademic(); }, dataError));
  state.unsubscribers.push(onSnapshot(collection(db, 'resultadosAprendizaje'), (snapshot) => { state.raps = ordered(snapshot); renderAcademic(); }, dataError));
  state.unsubscribers.push(onSnapshot(collection(db, 'asignacionesCompetencias'), (snapshot) => { state.rapAssignments = ordered(snapshot); renderAcademic(); }, dataError));
}
function dataError(error) { console.error(error); $('.live-dot').textContent = 'No se pudieron actualizar los datos'; }
function formFeedback(form, message, type = 'success') { if (!form) return; let feedback = form.querySelector('.inline-form-message'); if (!feedback) { feedback = document.createElement('p'); feedback.className = 'inline-form-message'; form.append(feedback); } feedback.textContent = message; feedback.dataset.type = type; }
function actionError(error, fallback, form) { console.error(error); formFeedback(form, error?.code === 'permission-denied' ? 'No tienes permisos para esta acción. Actualiza la página e inicia sesión de nuevo.' : fallback, 'error'); }
function normalizeTrimesterLabels() { const heading = $('#trimestres .tab-heading p:last-child'); if (heading) heading.textContent = 'Crea trimestres y asígnalos a una o varias fichas.'; const kicker = $('#trimestres .current-term .card-kicker'); if (kicker) kicker.textContent = 'TRIMESTRE ACTUAL'; const label = $('#trimester-assignment-form label'); if (label?.firstChild) label.firstChild.nodeValue = '1. Trimestre creado'; }
normalizeTrimesterLabels();
function replacePeriodLabels(root = document.body) { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); const changes = []; while (walker.nextNode()) { const node = walker.currentNode; if (node.parentElement?.closest('script,style')) continue; const value = node.nodeValue; const next = value.replace(/periodos/gi, 'trimestres').replace(/periodo/gi, 'trimestre'); if (next !== value) changes.push([node, next]); } changes.forEach(([node, value]) => { node.nodeValue = value; }); }
replacePeriodLabels();
function renderSummary() { const pending = state.users.filter((user) => !String(user.rol || '').trim()).length; const activeSheets = state.fichas.filter((item) => item.estado !== 'Inactiva'); const termsToReview = activeSheets.filter((sheet) => !sheet.trimestreId).length; $('#stat-users').textContent = state.users.length; $('#stat-fichas').textContent = activeSheets.length; $('#stat-programas').textContent = state.programas.filter((item) => item.estado !== 'Inactivo').length; $('#stat-verified').textContent = `${state.users.filter((user) => user.correoVerificado).length} correos verificados`; $('#pending-count').textContent = pending; if ($('#news-list')) { const items = [{ icon: '♙', title: 'Usuarios pendientes de rol', detail: pending ? 'Hay cuentas verificadas esperando una clasificación.' : 'No hay cuentas pendientes por clasificar.', value: pending, tab: 'usuarios' }, { icon: '◷', title: 'Trimestres por revisar', detail: termsToReview ? 'Hay fichas sin trimestre asignado.' : 'Todas las fichas activas tienen un trimestre.', value: termsToReview, tab: 'trimestres' }, { icon: '♧', title: 'Asignaciones académicas', detail: 'Consulta instructores y pasantes vinculados por ficha.', value: activeSheets.filter((sheet) => (sheet.instructorUids || []).length || (sheet.pasantesUids || []).length).length, tab: 'academico' }, { icon: '▣', title: 'Fichas activas', detail: 'Fichas disponibles para seguimiento académico.', value: activeSheets.length, tab: 'academico' }]; $('#news-list').innerHTML = items.map((item) => `<button class="news-item" data-go-tab="${item.tab}"><span class="news-icon">${item.icon}</span><span><b>${item.title}</b><small>${item.detail}</small></span><strong>${item.value} ›</strong></button>`).join(''); document.querySelectorAll('#news-list [data-go-tab]').forEach((button) => button.addEventListener('click', () => changeTab(button.dataset.goTab))); } }
function renderUsers() {
  const term = $('#user-search')?.value.toLowerCase().trim() || ''; const users = state.users.filter((user) => `${user.nombre || ''} ${user.correo || ''}`.toLowerCase().includes(term));
  $('#users-list').innerHTML = users.length ? users.map((user) => `<article class="user-row"><div class="user-name"><span>${text(initials(user.nombre))}</span><b>${text(user.nombre || 'Sin nombre')}<small>${user.correoVerificado ? 'Correo verificado' : 'Correo sin verificar'}</small></b></div><p>${text(user.correo || '—')}</p><p><span class="role-badge ${normalRole(user.rol) || 'pending'}">${text(user.rol || 'Pendiente')}</span></p><label class="role-select"><select data-user-id="${text(user.id)}" ${user.correoVerificado ? '' : 'disabled'}><option value="">${user.correoVerificado ? 'Asignar rol' : 'Verifica correo'}</option>${['Administrador', 'Instructor', 'Aprendiz', 'Pasante'].map((role) => `<option ${user.rol === role ? 'selected' : ''}>${role}</option>`).join('')}</select></label><span class="user-actions"><button data-user-disable="${text(user.id)}">${user.estado === 'suspendido' ? 'Activar' : 'Desactivar'}</button><button class="danger" data-user-delete="${text(user.id)}">Eliminar</button></span></article>`).join('') : '<p class="table-loading">No encontramos usuarios.</p>';
  document.querySelectorAll('[data-user-id]').forEach((select) => select.addEventListener('change', assignRole));
  document.querySelectorAll('[data-user-disable]').forEach((button) => button.onclick = () => toggleUser(button.dataset.userDisable));
  document.querySelectorAll('[data-user-delete]').forEach((button) => button.onclick = () => removeUser(button.dataset.userDelete));
}
async function assignRole(event) { const { value, dataset } = event.currentTarget; if (!value) return; event.currentTarget.disabled = true; try { await updateDoc(doc(db, 'usuarios', dataset.userId), { rol: value, actualizadoEn: new Date() }); } catch { alert('No fue posible asignar el rol. Verifica tus permisos.'); event.currentTarget.disabled = false; } }
async function toggleUser(id) { const user = state.users.find((item) => item.id === id); if (!user) return; const suspend = user.estado !== 'suspendido'; if (!confirm(`${suspend ? 'Desactivar' : 'Activar'} a ${user.nombre || 'este usuario'}?`)) return; await updateDoc(doc(db, 'usuarios', id), { estado: suspend ? 'suspendido' : 'activo', actualizadoEn: new Date() }); }
async function removeUser(id) { const user = state.users.find((item) => item.id === id); if (!user || !confirm(`Eliminar definitivamente el perfil de ${user.nombre || 'este usuario'}? Esta acción no se puede deshacer.`)) return; try { await deleteDoc(doc(db, 'usuarios', id)); } catch { alert('No fue posible eliminar el usuario.'); } }
function activePrograms() { return state.programas.filter((item) => item.estado !== 'Inactivo'); }
function programOptions(selected = '') { return activePrograms().map((item) => `<option value="${text(item.id)}" ${item.id === selected ? 'selected' : ''}>${text(item.nombre || 'Programa sin nombre')}</option>`).join(''); }
function fichaOptions(programaId = '', selected = '') { return state.fichas.filter((item) => item.estado !== 'Inactiva' && (!programaId || item.programaId === programaId)).map((item) => `<option value="${text(item.id)}" ${item.id === selected ? 'selected' : ''}>Ficha ${text(item.numero || 'sin número')}</option>`).join(''); }
function validTrimester(item) { return typeof item.fechaInicio === 'string' && typeof item.fechaFin === 'string'; }
function recordControls(type, item) { const disabled = item.estado === 'Inactivo' || item.estado === 'Inactiva'; return `<span class="record-actions"><button data-edit="${type}" data-id="${text(item.id)}">Editar</button><button data-disable="${type}" data-id="${text(item.id)}" ${disabled ? 'disabled' : ''}>${disabled ? 'Inactivo' : 'Desactivar'}</button><button class="danger" data-delete="${type}" data-id="${text(item.id)}">Eliminar</button></span>`; }
function renderAcademic() {
  $('#programas-count').textContent = state.programas.length;
  $('#fichas-count').textContent = state.fichas.length;
  $('#ficha-programa').innerHTML = '<option value="">Selecciona un programa</option>' + programOptions(state.editingFicha?.programaId);
  $('#programas-records').innerHTML = state.programas.length ? state.programas.map((item) => `<article class="record-line"><div class="record-info"><b>${text(item.nombre || 'Programa sin nombre')}</b><small>Código ${text(item.codigo || 'Sin código')}</small></div><span class="record-status ${item.estado === 'Inactivo' ? 'inactive' : ''}">${text(item.estado || 'Activo')}</span>${recordControls('programa', item)}</article>`).join('') : '<p class="empty-records">Aún no hay programas registrados.</p>';
  $('#fichas-records').innerHTML = state.fichas.length ? state.fichas.map((item) => `<article class="record-line"><div class="record-info"><b>Ficha ${text(item.numero || 'sin número')}</b><small>${text(item.programaNombre || 'Programa sin asignar')}</small></div><span class="record-status ${item.estado === 'Inactiva' ? 'inactive' : ''}">${text(item.estado || 'Activa')}</span>${recordControls('ficha', item)}</article>`).join('') : '<p class="empty-records">Aún no hay fichas registradas.</p>';
  if ($('#fichas-management-records')) $('#fichas-management-records').innerHTML = $('#fichas-records').innerHTML;
  renderCompetencias();
  bindRecordControls();
  renderAssignments();
}
function activeCompetencias() { return state.competencias.filter((item) => item.estado !== 'Inactiva' && item.activo !== false); }
function renderCompetencias() {
  if (!$('#competencia-programa')) return;
  const selectedProgram = $('#competencia-programa').value;
  $('#competencia-programa').innerHTML = '<option value="">Selecciona un programa</option>' + programOptions(selectedProgram);
  const selectedCompetencia = $('#rap-competencia').value;
  $('#rap-competencia').innerHTML = '<option value="">Selecciona una competencia</option>' + activeCompetencias().map((item) => `<option value="${text(item.id)}" ${item.id === selectedCompetencia ? 'selected' : ''}>${text(item.codigo)} · ${text(item.nombre)}</option>`).join('');
  $('#competencias-records').innerHTML = state.competencias.length ? state.competencias.map((item) => `<article class="record-line"><div class="record-info"><b>${text(item.codigo || 'Sin código')} · ${text(item.nombre)}</b><small>${text(item.descripcion || 'Sin descripción')}</small></div><span class="record-status ${item.estado === 'Inactiva' ? 'inactive' : ''}">${text(item.estado || 'Activa')}</span>${recordControls('competencia', item)}</article>`).join('') : '<p class="empty-records">Aún no hay competencias.</p>';
  const competenciaById = Object.fromEntries(state.competencias.map((item) => [item.id, item]));
  $('#raps-records').innerHTML = state.raps.length ? state.raps.map((item) => `<article class="record-line"><div class="record-info"><b>${text(item.codigo || 'RAP')} · ${text(item.descripcion || '')}</b><small>${text(competenciaById[item.competenciaId]?.nombre || 'Competencia no disponible')}</small></div><span class="record-status ${item.estado === 'Inactivo' ? 'inactive' : ''}">${text(item.estado || 'Activo')}</span>${recordControls('rap', item)}</article>`).join('') : '<p class="empty-records">Aún no hay RAP registrados.</p>';
  renderRapAssignments();
}
function renderRapAssignments() {
  if (!$('#rap-instructor')) return;
  const selected = { instructor: $('#rap-instructor').value, ficha: $('#rap-ficha').value, competencia: $('#rap-assignment-competencia').value, resultado: $('#rap-assignment-result').value };
  $('#rap-instructor').innerHTML = '<option value="">Selecciona un instructor</option>' + userAssignmentOptions('instructor');
  $('#rap-ficha').innerHTML = '<option value="">Selecciona una ficha</option>' + fichaAssignmentOptions();
  $('#rap-assignment-competencia').innerHTML = '<option value="">Selecciona una competencia</option>' + activeCompetencias().map((item) => `<option value="${text(item.id)}">${text(item.codigo)} · ${text(item.nombre)}</option>`).join('');
  $('#rap-instructor').value = selected.instructor; $('#rap-ficha').value = selected.ficha; $('#rap-assignment-competencia').value = selected.competencia;
  const matchingRaps = state.raps.filter((item) => [item.competenciaId, item.competencia?.id, item.competencia].includes(selected.competencia) && item.estado !== 'Inactivo' && item.activo !== false);
  $('#rap-assignment-result').innerHTML = '<option value="">Selecciona un RAP</option>' + matchingRaps.map((item) => `<option value="${text(item.id)}">${text(item.codigo)} · ${text(item.descripcion)}</option>`).join('');
  $('#rap-assignment-result').value = selected.resultado;
  const users = Object.fromEntries(state.users.map((item) => [item.id, item.nombre || item.correo || 'Usuario'])); const fichas = Object.fromEntries(state.fichas.map((item) => [item.id, `Ficha ${item.numero || 'sin número'}`])); const raps = Object.fromEntries(state.raps.map((item) => [item.id, item.codigo || 'RAP']));
  $('#rap-assignments-records').innerHTML = state.rapAssignments.length ? state.rapAssignments.map((item) => `<article class="assignment-record"><b>${text(fichas[item.fichaId] || 'Ficha')}</b><small>${text(users[item.instructorUid] || 'Instructor')}</small><p><span>RAP</span> ${text(raps[item.resultadoId] || 'Sin RAP')}</p>${recordControls('rapAssignment', item)}</article>`).join('') : '<p class="empty-records">Aún no hay RAP asignados.</p>';
}
function roleUsers(role) { return state.users.filter((user) => normalRole(user.rol) === role && user.correoVerificado); }
function fichaAssignmentOptions() { return state.fichas.filter((item) => item.estado !== 'Inactiva').map((item) => `<option value="${text(item.id)}">Ficha ${text(item.numero || 'sin número')} · ${text(item.programaNombre || 'Sin programa')}</option>`).join(''); }
function userAssignmentOptions(role) { return roleUsers(role).map((user) => `<option value="${text(user.id)}">${text(user.nombre || user.correo || 'Usuario')}</option>`).join(''); }
function renderAssignments() {
  if (!$('#assignment-instructor')) return;
  const selected = { instructor: $('#assignment-instructor').value, instructorFicha: $('#assignment-instructor-ficha').value, pasante: $('#assignment-pasante').value, pasanteFicha: $('#assignment-pasante-ficha').value };
  $('#assignment-instructor').innerHTML = '<option value="">Selecciona un instructor</option>' + userAssignmentOptions('instructor');
  $('#assignment-pasante').innerHTML = '<option value="">Selecciona un pasante</option>' + userAssignmentOptions('pasante');
  const fichas = fichaAssignmentOptions(); $('#assignment-instructor-ficha').innerHTML = '<option value="">Selecciona una ficha</option>' + fichas; $('#assignment-pasante-ficha').innerHTML = '<option value="">Selecciona una ficha</option>' + fichas;
  $('#assignment-instructor').value = selected.instructor; $('#assignment-instructor-ficha').value = selected.instructorFicha; $('#assignment-pasante').value = selected.pasante; $('#assignment-pasante-ficha').value = selected.pasanteFicha;
  const lookup = Object.fromEntries(state.users.map((user) => [user.id, user.nombre || user.correo || 'Usuario']));
  $('#assignments-records').innerHTML = state.fichas.length ? state.fichas.map((ficha) => { const instructors = (ficha.instructorUids || []).map((id) => lookup[id] || 'Instructor').join(', ') || 'Sin instructor'; const pasantes = (ficha.pasantesUids || []).map((id) => lookup[id] || 'Pasante').join(', ') || 'Sin pasante'; return `<article class="assignment-record"><b>Ficha ${text(ficha.numero || 'sin número')}</b><small>${text(ficha.programaNombre || 'Sin programa')}</small><p><span>Instructor</span> ${text(instructors)}</p><p><span>Pasante</span> ${text(pasantes)}</p></article>`; }).join('') : '<p class="empty-records">Crea una ficha para realizar asignaciones.</p>';
}
function selectedTermSheetIds() { return [...document.querySelectorAll('[data-term-sheet]:checked')].map((input) => input.value); }
function renderTrimester() {
  if (!$('#assignment-trimester')) return;
  const activeTerms = state.trimestres.filter((item) => item.estado !== 'Inactivo' && validTrimester(item));
  const currentSelection = $('#assignment-trimester').value;
  $('#assignment-trimester').innerHTML = '<option value="">Selecciona un trimestre</option>' + activeTerms.map((item) => `<option value="${text(item.id)}" ${item.id === currentSelection ? 'selected' : ''}>${text(item.fechaInicio)} a ${text(item.fechaFin)}</option>`).join('');
  const now = new Date(); const current = activeTerms.find((item) => new Date(`${item.fechaInicio}T00:00:00`) <= now && new Date(`${item.fechaFin}T23:59:59`) >= now);
  $('#current-trimester-title').textContent = current ? `Trimestre activo · ${current.fechaInicio} a ${current.fechaFin}` : 'Sin trimestre activo';
  $('#current-trimester-copy').textContent = current ? 'Asigna este trimestre a las fichas que correspondan para sincronizar la plataforma.' : 'Crea un trimestre y asígnalo a las fichas que correspondan.';
  renderTermSheets(); renderSheetSummary();
}
function renderTermSheets() { if (!$('#term-sheet-picker')) return; const search = ($('#term-sheet-search').value || '').toLowerCase(); const selected = new Set(selectedTermSheetIds()); const sheets = state.fichas.filter((item) => item.estado !== 'Inactiva' && `${item.numero || ''} ${item.programaNombre || ''}`.toLowerCase().includes(search)); $('#term-sheet-picker').innerHTML = sheets.length ? sheets.map((item) => `<label class="term-sheet-option"><input type="checkbox" data-term-sheet value="${text(item.id)}" ${selected.has(item.id) ? 'checked' : ''}/><span><b>Ficha ${text(item.numero || 'sin número')}</b><small>${text(item.programaNombre || 'Sin programa')}</small></span></label>`).join('') : '<p class="empty-records">No encontramos fichas.</p>'; document.querySelectorAll('[data-term-sheet]').forEach((input) => input.addEventListener('change', renderTermAssignmentSummary)); renderTermAssignmentSummary(); }
function renderTermAssignmentSummary() { if (!$('#term-assignment-summary')) return; const amount = selectedTermSheetIds().length; const term = state.trimestres.find((item) => item.id === $('#assignment-trimester').value); const number = $('#assignment-trimester-number').value || '—'; $('#term-assignment-summary').textContent = term ? `${amount} ficha(s) → Trimestre ${number} (${term.fechaInicio} a ${term.fechaFin})` : 'Selecciona un trimestre y una o varias fichas.'; }
function renderSheetSummary() { if (!$('#sheet-term-summary')) return; const termById = Object.fromEntries(state.trimestres.map((item) => [item.id, item])); const search = ($('#term-summary-search').value || '').toLowerCase(); const sheets = state.fichas.filter((item) => `${item.numero || ''} ${item.programaNombre || ''} ${item.trimestreActual || ''}`.toLowerCase().includes(search)).sort((a, b) => { const aDate = a.actualizadoEn?.toMillis?.() || Date.parse(a.trimestreFechaInicio || 0) || 0; const bDate = b.actualizadoEn?.toMillis?.() || Date.parse(b.trimestreFechaInicio || 0) || 0; return bDate - aDate; }); $('#sheet-term-summary').innerHTML = sheets.length ? sheets.map((sheet) => { const term = termById[sheet.trimestreId]; const assigned = Boolean(sheet.trimestreId || sheet.trimestreActual); return `<article class="sheet-term-card"><div><b>Ficha ${text(sheet.numero || 'sin número')}</b><small>${text(sheet.programaNombre || 'Sin programa')}</small></div><span class="${assigned ? 'assigned' : 'unassigned'}">${assigned ? text(sheet.trimestreActual || `Trimestre ${term?.numero || '?'}`) : 'Sin asignar'}</span><dl><div><dt>Inicio</dt><dd>${text(sheet.trimestreFechaInicio || term?.fechaInicio || 'Pendiente')}</dd></div><div><dt>Fin</dt><dd>${text(sheet.trimestreFechaFin || term?.fechaFin || 'Pendiente')}</dd></div><div><dt>Equipo</dt><dd>${(sheet.instructorUids || []).length} instructor(es) · ${(sheet.pasantesUids || []).length} pasante(s)</dd></div></dl></article>`; }).join('') : '<p class="empty-records">No encontramos fichas.</p>'; }
function resetProgram() { state.editingProgram = null; $('#program-form').reset(); $('#program-form-mode').textContent = 'NUEVO PROGRAMA'; $('#program-form-title').textContent = 'Crear programa'; $('#program-submit').innerHTML = 'Guardar programa <span>→</span>'; }
function resetFicha() { state.editingFicha = null; $('#ficha-form').reset(); $('#ficha-form-mode').textContent = 'NUEVA FICHA'; $('#ficha-form-title').textContent = 'Crear ficha'; $('#ficha-submit').innerHTML = 'Guardar ficha <span>→</span>'; renderAcademic(); }
function resetTrimester() { state.editingTrimester = null; $('#trimester-form').reset(); $('#trimester-form-mode').textContent = 'NUEVO TRIMESTRE'; $('#trimester-form-title').textContent = 'Crear trimestre'; $('#trimester-submit').innerHTML = 'Guardar trimestre <span>→</span>'; renderTrimester(); }
function bindRecordControls() {
  document.querySelectorAll('[data-edit]').forEach((button) => button.onclick = () => editRecord(button.dataset.edit, button.dataset.id));
  document.querySelectorAll('[data-disable]').forEach((button) => button.onclick = () => disableRecord(button.dataset.disable, button.dataset.id));
  document.querySelectorAll('[data-delete]').forEach((button) => button.onclick = () => deleteRecord(button.dataset.delete, button.dataset.id));
}
function editRecord(type, id) {
  const item = ({ programa: state.programas, ficha: state.fichas, trimestre: state.trimestres })[type]?.find((record) => record.id === id); if (!item) return;
  if (type === 'programa') { state.editingProgram = item; const form = $('#program-form'); form.nombre.value = item.nombre || ''; form.codigo.value = item.codigo || ''; $('#program-form-mode').textContent = 'EDITANDO PROGRAMA'; $('#program-form-title').textContent = 'Actualizar programa'; $('#program-submit').innerHTML = 'Actualizar programa <span>→</span>'; changeTab('academico'); setAcademicView('programas'); }
  if (type === 'ficha') { state.editingFicha = item; const form = $('#ficha-form'); form.numero.value = item.numero || ''; renderAcademic(); $('#ficha-programa').value = item.programaId || ''; $('#ficha-form-mode').textContent = 'EDITANDO FICHA'; $('#ficha-form-title').textContent = 'Actualizar ficha'; $('#ficha-submit').innerHTML = 'Actualizar ficha <span>→</span>'; changeTab('academico'); setAcademicView('fichas'); }
  if (type === 'trimestre') { state.editingTrimester = item; const form = $('#trimester-form'); form.numero.value = item.numero || ''; form.fechaInicio.value = item.fechaInicio || ''; form.fechaFin.value = item.fechaFin || ''; renderTrimester(); $('#trimester-programa').value = item.programaId || ''; $('#trimester-ficha').value = item.fichaId || ''; $('#trimester-form-mode').textContent = 'EDITANDO TRIMESTRE'; $('#trimester-form-title').textContent = 'Actualizar trimestre'; $('#trimester-submit').innerHTML = 'Actualizar trimestre <span>→</span>'; changeTab('trimestres'); }
}
async function disableRecord(type, id) { const collectionName = { programa: 'programas', ficha: 'fichas', trimestre: 'trimestres', competencia: 'competencias', rap: 'resultadosAprendizaje', rapAssignment: 'asignacionesCompetencias' }[type]; const estado = type === 'ficha' || type === 'competencia' || type === 'rapAssignment' ? 'Inactiva' : 'Inactivo'; if (!collectionName || !confirm('¿Deseas desactivar este registro? Seguirá guardado en la base de datos.')) return; try { await updateDoc(doc(db, collectionName, id), { estado, activo: false, actualizadoEn: new Date() }); } catch { alert('No fue posible desactivar el registro.'); } }
async function deleteRecord(type, id) { const collectionName = { programa: 'programas', ficha: 'fichas', trimestre: 'trimestres', competencia: 'competencias', rap: 'resultadosAprendizaje', rapAssignment: 'asignacionesCompetencias' }[type]; if (!collectionName || !confirm('¿Eliminar definitivamente este registro? Esta acción no se puede deshacer.')) return; try { await deleteDoc(doc(db, collectionName, id)); } catch { alert('No fue posible eliminar el registro.'); } }
$('#user-search')?.addEventListener('input', renderUsers);
$('#program-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { nombre: String(form.get('nombre')).trim(), codigo: String(form.get('codigo')).trim().toUpperCase(), actualizadoEn: new Date() }; try { if (state.editingProgram) await updateDoc(doc(db, 'programas', state.editingProgram.id), payload); else await addDoc(collection(db, 'programas'), { ...payload, estado: 'Activo', creadoEn: new Date() }); resetProgram(); } catch { alert('No fue posible guardar el programa.'); } });
$('#ficha-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const programa = state.programas.find((item) => item.id === form.get('programaId')); if (!programa) return alert('Selecciona un programa activo.'); const payload = { numero: String(form.get('numero')).trim(), programaId: programa.id, programaNombre: programa.nombre, actualizadoEn: new Date() }; try { if (state.editingFicha) await updateDoc(doc(db, 'fichas', state.editingFicha.id), payload); else await addDoc(collection(db, 'fichas'), { ...payload, estado: 'Activa', creadoEn: new Date() }); resetFicha(); } catch { alert('No fue posible guardar la ficha.'); } });
$('#competencia-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const programa = state.programas.find((item) => item.id === $('#competencia-programa').value); if (!programa) return formFeedback(event.currentTarget, 'Selecciona un programa.', 'error'); const payload = { programaId: programa.id, programaNombre: programa.nombre, codigo: String(form.get('codigo')).trim().toUpperCase(), nombre: String(form.get('nombre')).trim(), descripcion: String(form.get('descripcion')).trim(), activo: true, estado: 'Activa', creadoEn: new Date(), actualizadoEn: new Date() }; try { await addDoc(collection(db, 'competencias'), payload); event.currentTarget.reset(); formFeedback(event.currentTarget, 'Competencia guardada correctamente.'); } catch (error) { actionError(error, 'No fue posible guardar la competencia.', event.currentTarget); } });
$('#rap-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const competenciaId = $('#rap-competencia').value; if (!competenciaId) return formFeedback(event.currentTarget, 'Selecciona una competencia.', 'error'); const payload = { competenciaId, codigo: String(form.get('codigo')).trim().toUpperCase(), descripcion: String(form.get('descripcion')).trim(), activo: true, estado: 'Activo', creadoEn: new Date(), actualizadoEn: new Date() }; try { await addDoc(collection(db, 'resultadosAprendizaje'), payload); event.currentTarget.reset(); formFeedback(event.currentTarget, 'RAP guardado correctamente.'); } catch (error) { actionError(error, 'No fue posible guardar el RAP.', event.currentTarget); } });
$('#rap-assignment-competencia')?.addEventListener('change', renderRapAssignments);
$('#rap-assignment-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const instructorUid = $('#rap-instructor').value; const fichaId = $('#rap-ficha').value; const competenciaId = $('#rap-assignment-competencia').value; const resultadoId = $('#rap-assignment-result').value; if (!instructorUid || !fichaId || !competenciaId || !resultadoId) return formFeedback(event.currentTarget, 'Completa instructor, ficha, competencia y RAP.', 'error'); const repeated = state.rapAssignments.some((item) => item.fichaId === fichaId && item.resultadoId === resultadoId && item.estado !== 'Inactiva' && item.activo !== false); if (repeated) return formFeedback(event.currentTarget, 'Este RAP ya está asignado a esa ficha.', 'error'); try { const batch = writeBatch(db); const assignmentRef = doc(collection(db, 'asignacionesCompetencias')); const now = new Date(); batch.set(assignmentRef, { instructorUid, fichaId, competenciaId, resultadoId, resultadoIds: [resultadoId], activo: true, estado: 'Activa', creadoEn: now, actualizadoEn: now }); batch.update(doc(db, 'fichas', fichaId), { instructorUids: arrayUnion(instructorUid), actualizadoEn: now }); batch.update(doc(db, 'usuarios', instructorUid), { fichasAsignadas: arrayUnion(fichaId), actualizadoEn: now }); await batch.commit(); event.currentTarget.reset(); formFeedback(event.currentTarget, 'RAP asignado correctamente.'); } catch (error) { actionError(error, 'No fue posible asignar el RAP.', event.currentTarget); } });
$('#trimester-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const fechaInicio = String(form.get('fechaInicio')); const fechaFin = String(form.get('fechaFin')); if (fechaInicio > fechaFin) return alert('La fecha de inicio no puede ser posterior a la fecha final.'); const payload = { fechaInicio, fechaFin, estado: 'Activo', activo: true, actualizadoEn: new Date() }; try { if (state.editingTrimester) await updateDoc(doc(db, 'trimestres', state.editingTrimester.id), payload); else await addDoc(collection(db, 'trimestres'), { ...payload, creadoEn: new Date() }); resetTrimester(); } catch { alert('No fue posible guardar el trimestre.'); } });
$('#trimester-assignment-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const trimesterId = $('#assignment-trimester').value; const numero = Number($('#assignment-trimester-number').value); const fichaIds = selectedTermSheetIds(); const trimester = state.trimestres.find((item) => item.id === trimesterId); if (!trimester || !numero || numero < 1 || !fichaIds.length) return alert('Selecciona un trimestre, escribe el número y elige al menos una ficha.'); try { const selectedSheets = state.fichas.filter((item) => fichaIds.includes(item.id)); await Promise.all(selectedSheets.map(async (sheet) => { const payload = { trimestreId: trimester.id, trimestreActual: `Trimestre ${numero}`, trimestreNumero: numero, trimestreFechaInicio: trimester.fechaInicio, trimestreFechaFin: trimester.fechaFin, actualizadoEn: new Date() }; await updateDoc(doc(db, 'fichas', sheet.id), payload); const usersToUpdate = state.users.filter((user) => user.fichaId === sheet.id || (user.fichasAsignadas || []).includes(sheet.id)); await Promise.all(usersToUpdate.map((user) => updateDoc(doc(db, 'usuarios', user.id), payload))); })); $('#term-assignment-summary').textContent = `Trimestre ${numero} asignado a ${selectedSheets.length} ficha(s).`; document.querySelectorAll('[data-term-sheet]').forEach((input) => { input.checked = false; }); } catch { alert('No fue posible asignar el trimestre a las fichas.'); } });
$('#assignment-trimester')?.addEventListener('change', renderTermAssignmentSummary); $('#assignment-trimester-number')?.addEventListener('input', renderTermAssignmentSummary); $('#term-sheet-search')?.addEventListener('input', renderTermSheets); $('#term-summary-search')?.addEventListener('input', renderSheetSummary);
$('#instructor-ficha-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const instructorUid = $('#assignment-instructor').value; const fichaId = $('#assignment-instructor-ficha').value; if (!instructorUid || !fichaId) return formFeedback(event.currentTarget, 'Selecciona un instructor y una ficha.', 'error'); try { const batch = writeBatch(db); const now = new Date(); batch.update(doc(db, 'fichas', fichaId), { instructorUids: arrayUnion(instructorUid), actualizadoEn: now }); batch.update(doc(db, 'usuarios', instructorUid), { fichasAsignadas: arrayUnion(fichaId), actualizadoEn: now }); await batch.commit(); event.currentTarget.reset(); formFeedback(event.currentTarget, 'Instructor asignado correctamente.'); } catch (error) { actionError(error, 'No fue posible guardar la asignación del instructor.', event.currentTarget); } });
$('#pasante-ficha-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const pasanteUid = $('#assignment-pasante').value; const fichaId = $('#assignment-pasante-ficha').value; if (!pasanteUid || !fichaId) return formFeedback(event.currentTarget, 'Selecciona un pasante y una ficha.', 'error'); try { const batch = writeBatch(db); const now = new Date(); batch.update(doc(db, 'usuarios', pasanteUid), { fichasAsignadas: arrayUnion(fichaId), actualizadoEn: now }); batch.update(doc(db, 'fichas', fichaId), { pasantesUids: arrayUnion(pasanteUid), actualizadoEn: now }); await batch.commit(); event.currentTarget.reset(); formFeedback(event.currentTarget, 'Pasante asignado correctamente.'); } catch (error) { actionError(error, 'No fue posible guardar la asignación del pasante.', event.currentTarget); } });
$('#profile-file')?.addEventListener('change', (event) => { const file = event.currentTarget.files?.[0]; if (!file) return; if (file.size > 650000) { $('#profile-message').textContent = 'La foto debe pesar menos de 650 KB.'; $('#profile-message').className = 'form-message error'; return; } const reader = new FileReader(); reader.onload = () => { state.pendingPhoto = reader.result; $('#profile-image').src = reader.result; $('#profile-image').hidden = false; $('#profile-initials').hidden = true; }; reader.readAsDataURL(file); });
$('#profile-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const nombre = $('#profile-name').value.trim(); if (!nombre || !auth.currentUser) return; const message = $('#profile-message'); message.textContent = 'Guardando cambios…'; message.className = 'form-message'; try { const updates = { nombre, actualizadoEn: new Date() }; if (state.pendingPhoto) updates.fotoUrl = state.pendingPhoto; await updateDoc(doc(db, 'usuarios', auth.currentUser.uid), updates); await updateProfile(auth.currentUser, { displayName: nombre }); state.profile = { ...state.profile, ...updates }; state.pendingPhoto = null; $('#account-name').textContent = nombre; $('#admin-short-name').textContent = nombre.split(' ')[0]; $('#account-avatar').textContent = initials(nombre); message.textContent = 'Perfil guardado en BioMind.'; } catch { message.textContent = 'No fue posible guardar el perfil.'; message.className = 'form-message error'; } });
$('#profile-sign-out')?.addEventListener('click', () => signOut(auth));
function setAcademicView(view) { document.querySelectorAll('.academic-view').forEach((element) => element.classList.toggle('active', element.id === `academic-${view}`)); document.querySelectorAll('[data-academic-view]').forEach((element) => element.classList.toggle('active', element.dataset.academicView === view)); }
document.querySelectorAll('[data-academic-view]').forEach((button) => button.addEventListener('click', () => setAcademicView(button.dataset.academicView)));
document.querySelectorAll('[data-cancel]').forEach((button) => button.addEventListener('click', () => ({ program: resetProgram, ficha: resetFicha, trimestre: resetTrimester })[button.dataset.cancel]()));
document.querySelectorAll('[data-tab]').forEach((button) => button.addEventListener('click', () => changeTab(button.dataset.tab))); document.querySelectorAll('[data-go-tab]').forEach((button) => button.addEventListener('click', () => changeTab(button.dataset.goTab)));
function changeTab(tab) { document.querySelectorAll('.admin-tab').forEach((element) => element.classList.toggle('active', element.id === tab)); document.querySelectorAll('[data-tab]').forEach((element) => element.classList.toggle('active', element.dataset.tab === tab)); $('#admin-title').textContent = 'Administración BioMind'; if (tab === 'perfil') renderProfile(); $('.admin-sidebar').classList.remove('open'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
$('#sign-out')?.addEventListener('click', () => signOut(auth)); $('.admin-menu')?.addEventListener('click', () => $('.admin-sidebar').classList.toggle('open'));
